name: Format, lint, test and build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  format-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Format
        run: npm run format
      - name: Lint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Collect test coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        if: always()
        with:
          test-script: npm run test:cov
          custom-title: Backend coverage report
  build:
    needs: [format-and-lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Prisma Migrate
        run: npx prisma migrate dev --preview-feature # en mode preview pour tester le build
        env:
          DATABASE_URL: file:./test.db
      - name: Prisma Generate
        run: npx prisma generate
        env:
          DATABASE_URL: file:./test.db
      - name: Build
        run: npm run build
        env:
          DATABASE_URL: file:./test.db
